blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/lucaruboni/Global_AI_adoption_heat_map/discussions
    about: Ask questions and discuss ideas with the community.
